import { ClaimData } from "@/types/claim";

export const seedData: ClaimData[] = [
  {
    "id": "vzsn8kk",
    "companyName": "Acko General Insurance Limited",
    "reportingDate": "14-07-2026",
    "createdBy": "NAGRAJ DESPANDE( 7304586172 )",
    "dailyClaimsReceived": "11",
    "dailyFirstVisitCompleted": "13",
    "dailyApproxClaimAmount": "1422119",
    "cumulativeClaimsReceived": "52",
    "cumulativeFirstVisitCompleted": "36",
    "cumulativeApproxClaimAmount": "7341181",
    "approvedClaimsCount": "8",
    "approvedClaimAmount": "46471",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "15-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "mtkz0wd",
    "companyName": "Bajaj Allianz General Insurance Company Limited",
    "reportingDate": "20-07-2026",
    "createdBy": "KETAN PATEL( 9974056780 )",
    "dailyClaimsReceived": "11",
    "dailyFirstVisitCompleted": "11",
    "dailyApproxClaimAmount": "430000",
    "cumulativeClaimsReceived": "538",
    "cumulativeFirstVisitCompleted": "538",
    "cumulativeApproxClaimAmount": "98000000",
    "approvedClaimsCount": "475",
    "approvedClaimAmount": "80000000",
    "motorWithdrawClaimsCount": "12",
    "rejectedClaimsCount": "-",
    "rejectionReason": "As of now Zero claim rejected.",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "21-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "jilndcs",
    "companyName": "BAJAJ GENERAL INSURANCE LIMITED/PROPERTY",
    "reportingDate": "17-07-2026",
    "createdBy": "NILESH BHARBHAYA( 9898991046 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "9",
    "propertyDailyFirstVisitCompleted": "9",
    "propertyDailyApproxClaimAmount": "3250000",
    "propertyCumulativeClaimsReceived": "392",
    "propertyCumulativeFirstVisitCompleted": "392",
    "propertyCumulativeApproxClaimAmount": "1124183003",
    "propertyApprovedClaimsCount": "244",
    "propertyApprovedClaimAmount": "54221064",
    "propertyRejectedClaimsCount": "37",
    "propertyWithdrawClaimsCount": "25",
    "propertyRejectionReason": "Mostly location issue",
    "createdDate": "18-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "uhwcm84",
    "companyName": "CHOLAMANDALAM MS GENERAL INSURANCE COMPANT LIMITED/PROPERTY",
    "reportingDate": "22-07-2026",
    "createdBy": "DARSHIT VORALIYA( 9998393891 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "1",
    "propertyDailyFirstVisitCompleted": "500000",
    "propertyDailyApproxClaimAmount": "500000",
    "propertyCumulativeClaimsReceived": "47",
    "propertyCumulativeFirstVisitCompleted": "47",
    "propertyCumulativeApproxClaimAmount": "62000000",
    "propertyApprovedClaimsCount": "25",
    "propertyApprovedClaimAmount": "11361915",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "2",
    "propertyRejectionReason": "-",
    "createdDate": "22-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "sghqukt",
    "companyName": "Cholamandalam MS General Insurance Company Limited",
    "reportingDate": "17-07-2026",
    "createdBy": "KRUPESH RAVAL( 9825498622 )",
    "dailyClaimsReceived": "30",
    "dailyFirstVisitCompleted": "30",
    "dailyApproxClaimAmount": "820000",
    "cumulativeClaimsReceived": "170",
    "cumulativeFirstVisitCompleted": "170",
    "cumulativeApproxClaimAmount": "120000",
    "approvedClaimsCount": "55",
    "approvedClaimAmount": "2510000",
    "motorWithdrawClaimsCount": "1",
    "rejectedClaimsCount": "-",
    "rejectionReason": "Insured withdrawn claim due to minor loss.",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "18-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "je2rx4z",
    "companyName": "GENERALI CENTRAL INSURANCE COMPANY LIMITED",
    "reportingDate": "14-07-2026",
    "createdBy": "VISHAL SINGH( 9099864385 )",
    "dailyClaimsReceived": "2",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "51",
    "cumulativeFirstVisitCompleted": "39",
    "cumulativeApproxClaimAmount": "8728000",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "15-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "d8mf46k",
    "companyName": "GENERALI CENTRAL INSURANCE COMPANY LIMITED/PROPERTY",
    "reportingDate": "21-07-2026",
    "createdBy": "GIRISH RATHORE( 8889907172 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "19",
    "propertyCumulativeFirstVisitCompleted": "18",
    "propertyCumulativeApproxClaimAmount": "26141286",
    "propertyApprovedClaimsCount": "8",
    "propertyApprovedClaimAmount": "7688130",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "5",
    "propertyRejectionReason": "-",
    "createdDate": "22-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "bmxmve8",
    "companyName": "Go Digit General Insurance Limited",
    "reportingDate": "17-07-2026",
    "createdBy": "GOKUL MEHTA( 8956271052 )",
    "dailyClaimsReceived": "35",
    "dailyFirstVisitCompleted": "35",
    "dailyApproxClaimAmount": "1000000",
    "cumulativeClaimsReceived": "650",
    "cumulativeFirstVisitCompleted": "590",
    "cumulativeApproxClaimAmount": "150000",
    "approvedClaimsCount": "325",
    "approvedClaimAmount": "4500000",
    "motorWithdrawClaimsCount": "12",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "18-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "a5t9z1c",
    "companyName": "GO DIGIT GENERAL INSURANCE LTD/PROPERTY",
    "reportingDate": "21-07-2026",
    "createdBy": "DHRUMIL SHAH ( 9426284439 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "42",
    "propertyCumulativeFirstVisitCompleted": "42",
    "propertyCumulativeApproxClaimAmount": "147198000",
    "propertyApprovedClaimsCount": "15",
    "propertyApprovedClaimAmount": "3036144",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "3",
    "propertyRejectionReason": "-",
    "createdDate": "22-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "x0ble3q",
    "companyName": "HDFC ERGO General Insurance Company Limited",
    "reportingDate": "16-07-2026",
    "createdBy": "Nayan Bhad( 9106825015 )",
    "dailyClaimsReceived": "5",
    "dailyFirstVisitCompleted": "5",
    "dailyApproxClaimAmount": "782942",
    "cumulativeClaimsReceived": "166",
    "cumulativeFirstVisitCompleted": "166",
    "cumulativeApproxClaimAmount": "86279689",
    "approvedClaimsCount": "165",
    "approvedClaimAmount": "69023751",
    "motorWithdrawClaimsCount": "1",
    "rejectedClaimsCount": "-",
    "rejectionReason": "Many vehicle under repair, we awaiting the invoices to settle the claims also salvage auction is under process for the total loss cases.",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "18-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "0db9s9w",
    "companyName": "HDFC ERGO General Insurance LTD / PROPERTY",
    "reportingDate": "10-07-2026",
    "createdBy": "Fidual Hoda( 8976965002 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "6",
    "propertyDailyFirstVisitCompleted": "6",
    "propertyDailyApproxClaimAmount": "2900000",
    "propertyCumulativeClaimsReceived": "22",
    "propertyCumulativeFirstVisitCompleted": "22",
    "propertyCumulativeApproxClaimAmount": "36116000",
    "propertyApprovedClaimsCount": "5",
    "propertyApprovedClaimAmount": "546000",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "15-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "bpdz3na",
    "companyName": "ICICI Lombard General Insurance Company Limited",
    "reportingDate": "17-07-2026",
    "createdBy": "RUSHABH SHAH( 9512100566 )",
    "dailyClaimsReceived": "71",
    "dailyFirstVisitCompleted": "71",
    "dailyApproxClaimAmount": "740000",
    "cumulativeClaimsReceived": "575",
    "cumulativeFirstVisitCompleted": "575",
    "cumulativeApproxClaimAmount": "97500000",
    "approvedClaimsCount": "65",
    "approvedClaimAmount": "6400000",
    "motorWithdrawClaimsCount": "8",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "18-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "l3f3mcq",
    "companyName": "ICICI LOMBARD GIC LTD/PROPERTY",
    "reportingDate": "20-07-2026",
    "createdBy": "HIREN MEGHPARA( 9136995417 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "12",
    "propertyDailyFirstVisitCompleted": "12",
    "propertyDailyApproxClaimAmount": "15692315",
    "propertyCumulativeClaimsReceived": "126",
    "propertyCumulativeFirstVisitCompleted": "126",
    "propertyCumulativeApproxClaimAmount": "187159450",
    "propertyApprovedClaimsCount": "83",
    "propertyApprovedClaimAmount": "44326765",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "8",
    "propertyRejectionReason": "NA",
    "createdDate": "20-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "6ts5gi6",
    "companyName": "IFFCO TOKIO GENERAL INSURANCE CO LTD/PROPERTY",
    "reportingDate": "23-07-2026",
    "createdBy": "ANIL BRAHMBHATT( 7043711500 )",
    "dailyClaimsReceived": "1",
    "dailyFirstVisitCompleted": "1",
    "dailyApproxClaimAmount": "50654",
    "cumulativeClaimsReceived": "68",
    "cumulativeFirstVisitCompleted": "68",
    "cumulativeApproxClaimAmount": "15332477",
    "approvedClaimsCount": "4",
    "approvedClaimAmount": "130629",
    "motorWithdrawClaimsCount": "1",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "5",
    "propertyDailyFirstVisitCompleted": "2",
    "propertyDailyApproxClaimAmount": "125000",
    "propertyCumulativeClaimsReceived": "168",
    "propertyCumulativeFirstVisitCompleted": "165",
    "propertyCumulativeApproxClaimAmount": "265873638",
    "propertyApprovedClaimsCount": "33",
    "propertyApprovedClaimAmount": "6277898",
    "propertyRejectedClaimsCount": "4",
    "propertyWithdrawClaimsCount": "17",
    "propertyRejectionReason": "no loss observed in 2 claims  Affected loss location is not covered in 1 claim.",
    "createdDate": "23-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "esffttw",
    "companyName": "INDUSLND GENERAL INSURANCE CO LTD",
    "reportingDate": "20-07-2026",
    "createdBy": "RANJIT DWIVEDI( 9136953241 )",
    "dailyClaimsReceived": "5",
    "dailyFirstVisitCompleted": "5",
    "dailyApproxClaimAmount": "2500000",
    "cumulativeClaimsReceived": "190",
    "cumulativeFirstVisitCompleted": "180",
    "cumulativeApproxClaimAmount": "32000000",
    "approvedClaimsCount": "9",
    "approvedClaimAmount": "20000",
    "motorWithdrawClaimsCount": "4",
    "rejectedClaimsCount": "1",
    "rejectionReason": "NCB falsified,",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "18-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "shekkte",
    "companyName": "INDUSLND GENERAL INSURANCE CO LTD/PROPERTY",
    "reportingDate": "23-07-2026",
    "createdBy": "RAMBABU PARIHAR( 9136653101 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "32",
    "propertyCumulativeFirstVisitCompleted": "32",
    "propertyCumulativeApproxClaimAmount": "134783000",
    "propertyApprovedClaimsCount": "1",
    "propertyApprovedClaimAmount": "451672",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "1",
    "propertyRejectionReason": "-",
    "createdDate": "23-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "k4ffybk",
    "companyName": "Kiwi General Insurance LTD MOTOR",
    "reportingDate": "18-07-2026",
    "createdBy": "ALAYKUMAR PATEL( 7211122888 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "No Claim Reported",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "18-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "qmlxtk0",
    "companyName": "Liberty General Insurance Company Limited",
    "reportingDate": "17-07-2026",
    "createdBy": "SARTHAK CHEVLI( 9712924459 )",
    "dailyClaimsReceived": "4",
    "dailyFirstVisitCompleted": "1",
    "dailyApproxClaimAmount": "1500000",
    "cumulativeClaimsReceived": "210",
    "cumulativeFirstVisitCompleted": "202",
    "cumulativeApproxClaimAmount": "45000000",
    "approvedClaimsCount": "79",
    "approvedClaimAmount": "20414653",
    "motorWithdrawClaimsCount": "10",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "18-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "upkb0kd",
    "companyName": "LIBERTY GENERAL INSURANCE LIMITED/PROPERTY",
    "reportingDate": "17-07-2026",
    "createdBy": "HARSHIT POKHARANA( 9806584560 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "3",
    "propertyCumulativeFirstVisitCompleted": "3",
    "propertyCumulativeApproxClaimAmount": "2200000",
    "propertyApprovedClaimsCount": "2",
    "propertyApprovedClaimAmount": "673000",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "18-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "kizzeqk",
    "companyName": "Magma general insurance limited",
    "reportingDate": "20-07-2026",
    "createdBy": "Sagar Shah( 9227120030 )",
    "dailyClaimsReceived": "129",
    "dailyFirstVisitCompleted": "129",
    "dailyApproxClaimAmount": "35657729",
    "cumulativeClaimsReceived": "129",
    "cumulativeFirstVisitCompleted": "129",
    "cumulativeApproxClaimAmount": "35657729",
    "approvedClaimsCount": "6",
    "approvedClaimAmount": "264965",
    "motorWithdrawClaimsCount": "5",
    "rejectedClaimsCount": "1",
    "rejectionReason": "Permit Invalid",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "20-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "uepoae5",
    "companyName": "NATIONAL INSURANCE COMPANY LIMITED",
    "reportingDate": "23-07-2026",
    "createdBy": "AJAY PARMAR( 7069037734 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "40",
    "propertyCumulativeFirstVisitCompleted": "40",
    "propertyCumulativeApproxClaimAmount": "72656078",
    "propertyApprovedClaimsCount": "5",
    "propertyApprovedClaimAmount": "625000",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "2",
    "propertyRejectionReason": "-",
    "createdDate": "23-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "amedrkr",
    "companyName": "National Insurance Company Limited",
    "reportingDate": "22-07-2026",
    "createdBy": "ASHOK RATHOD( 9099998514 )",
    "dailyClaimsReceived": "2",
    "dailyFirstVisitCompleted": "2",
    "dailyApproxClaimAmount": "1000000",
    "cumulativeClaimsReceived": "61",
    "cumulativeFirstVisitCompleted": "61",
    "cumulativeApproxClaimAmount": "20697781",
    "approvedClaimsCount": "9",
    "approvedClaimAmount": "1173928",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "23-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "pr7ir80",
    "companyName": "Royal Sundaram General Insurance Company Limited",
    "reportingDate": "16-07-2026",
    "createdBy": "Tejas Pothiwala( 9727773918 )",
    "dailyClaimsReceived": "10",
    "dailyFirstVisitCompleted": "26",
    "dailyApproxClaimAmount": "3500000",
    "cumulativeClaimsReceived": "132",
    "cumulativeFirstVisitCompleted": "123",
    "cumulativeApproxClaimAmount": "22000000",
    "approvedClaimsCount": "48",
    "approvedClaimAmount": "56500",
    "motorWithdrawClaimsCount": "6",
    "rejectedClaimsCount": "-",
    "rejectionReason": "NA",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "16-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "gdwkdx6",
    "companyName": "SBI GENERAL INSURANCE CO LTD",
    "reportingDate": "14-07-2026",
    "createdBy": "MOHAN KAMATH( 7676866536 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "40",
    "propertyDailyFirstVisitCompleted": "40",
    "propertyDailyApproxClaimAmount": "60000000",
    "propertyCumulativeClaimsReceived": "40",
    "propertyCumulativeFirstVisitCompleted": "40",
    "propertyCumulativeApproxClaimAmount": "51500000",
    "propertyApprovedClaimsCount": "3",
    "propertyApprovedClaimAmount": "515000",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "1",
    "propertyRejectionReason": "-",
    "createdDate": "14-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "0qzczv0",
    "companyName": "SBI General Insurance Company Limited",
    "reportingDate": "17-07-2026",
    "createdBy": "KRUNAL PANCHAL( 8655389758 )",
    "dailyClaimsReceived": "1",
    "dailyFirstVisitCompleted": "1",
    "dailyApproxClaimAmount": "400000",
    "cumulativeClaimsReceived": "121",
    "cumulativeFirstVisitCompleted": "113",
    "cumulativeApproxClaimAmount": "18628354",
    "approvedClaimsCount": "45",
    "approvedClaimAmount": "3500000",
    "motorWithdrawClaimsCount": "1",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "17-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "3c6yrq9",
    "companyName": "Shriram General Insurance Company Limited",
    "reportingDate": "20-07-2026",
    "createdBy": "KUSHAL DESAI( 7043532598 )",
    "dailyClaimsReceived": "1",
    "dailyFirstVisitCompleted": "1",
    "dailyApproxClaimAmount": "40000",
    "cumulativeClaimsReceived": "21",
    "cumulativeFirstVisitCompleted": "21",
    "cumulativeApproxClaimAmount": "1527500",
    "approvedClaimsCount": "16",
    "approvedClaimAmount": "1053000",
    "motorWithdrawClaimsCount": "5",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "1",
    "propertyDailyFirstVisitCompleted": "1",
    "propertyDailyApproxClaimAmount": "25000",
    "propertyCumulativeClaimsReceived": "1",
    "propertyCumulativeFirstVisitCompleted": "1",
    "propertyCumulativeApproxClaimAmount": "25000",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "1",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "Location not cover under the policy",
    "createdDate": "21-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "7krtjt4",
    "companyName": "Tata AIG General Insurance Company Limited",
    "reportingDate": "22-07-2026",
    "createdBy": "SHREY PANDYA( 9638990052 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "2",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "540",
    "cumulativeFirstVisitCompleted": "540",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "369",
    "approvedClaimAmount": "73000000",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "23-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "e32nuxv",
    "companyName": "TATA AIG GENERAL INSURANCE COMPANY/PROPERTY",
    "reportingDate": "23-07-2026",
    "createdBy": "PRATIK GOHEL( 9099065735 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "36",
    "propertyCumulativeFirstVisitCompleted": "36",
    "propertyCumulativeApproxClaimAmount": "3500000",
    "propertyApprovedClaimsCount": "21",
    "propertyApprovedClaimAmount": "7402000",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "1",
    "propertyRejectionReason": "-",
    "createdDate": "23-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "oyxy6ou",
    "companyName": "The New India Assurance Company Limited",
    "reportingDate": "21-07-2026",
    "createdBy": "DEEPAM POPAT( 9978970380 )",
    "dailyClaimsReceived": "2",
    "dailyFirstVisitCompleted": "2",
    "dailyApproxClaimAmount": "200000",
    "cumulativeClaimsReceived": "245",
    "cumulativeFirstVisitCompleted": "245",
    "cumulativeApproxClaimAmount": "83200000",
    "approvedClaimsCount": "4",
    "approvedClaimAmount": "95952",
    "motorWithdrawClaimsCount": "1",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "462",
    "propertyCumulativeFirstVisitCompleted": "462",
    "propertyCumulativeApproxClaimAmount": "1615000000",
    "propertyApprovedClaimsCount": "8",
    "propertyApprovedClaimAmount": "2235052",
    "propertyRejectedClaimsCount": "3",
    "propertyWithdrawClaimsCount": "16",
    "propertyRejectionReason": "-",
    "createdDate": "21-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "hydnri8",
    "companyName": "The Oriental Insurance Company Limited",
    "reportingDate": "21-07-2026",
    "createdBy": "SHUBHAM SHARMA( 9671779713 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "36",
    "cumulativeFirstVisitCompleted": "36",
    "cumulativeApproxClaimAmount": "17341576",
    "approvedClaimsCount": "1",
    "approvedClaimAmount": "449000",
    "motorWithdrawClaimsCount": "1",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "57",
    "propertyCumulativeFirstVisitCompleted": "57",
    "propertyCumulativeApproxClaimAmount": "45485000",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "2",
    "propertyRejectionReason": "-",
    "createdDate": "21-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "s5qleyd",
    "companyName": "UNITED INDIA INSURANCE CO LTD/PROPERTY",
    "reportingDate": "22-07-2026",
    "createdBy": "KRUNAL JADAV( 8866137505 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "80",
    "propertyCumulativeFirstVisitCompleted": "80",
    "propertyCumulativeApproxClaimAmount": "242831308",
    "propertyApprovedClaimsCount": "36",
    "propertyApprovedClaimAmount": "4700933",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "7",
    "propertyRejectionReason": "-",
    "createdDate": "22-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "bzgxo3v",
    "companyName": "United India Insurance Company Limited",
    "reportingDate": "23-07-2026",
    "createdBy": "SURESH BHOJWANI( 9879251200 )",
    "dailyClaimsReceived": "2",
    "dailyFirstVisitCompleted": "2",
    "dailyApproxClaimAmount": "860000",
    "cumulativeClaimsReceived": "39",
    "cumulativeFirstVisitCompleted": "39",
    "cumulativeApproxClaimAmount": "14779224",
    "approvedClaimsCount": "15",
    "approvedClaimAmount": "1542800",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "23-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "bxyy9av",
    "companyName": "Zuno General Insurance Limited (formerly Edelweiss General Insurance)",
    "reportingDate": "24-07-2026",
    "createdBy": "ROHITDAS DUDHREJIYA( 8160989905 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "29",
    "cumulativeFirstVisitCompleted": "29",
    "cumulativeApproxClaimAmount": "7170000",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "24-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "6djh5t6",
    "companyName": "ZURICH KOTAK GENERAL INSURANCE COMPANY INDIA LTD/PROPERTY",
    "reportingDate": "21-07-2026",
    "createdBy": "BHAVIN SHAH( 8530870049 )",
    "dailyClaimsReceived": "-",
    "dailyFirstVisitCompleted": "-",
    "dailyApproxClaimAmount": "-",
    "cumulativeClaimsReceived": "-",
    "cumulativeFirstVisitCompleted": "-",
    "cumulativeApproxClaimAmount": "-",
    "approvedClaimsCount": "-",
    "approvedClaimAmount": "-",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "18",
    "propertyCumulativeFirstVisitCompleted": "18",
    "propertyCumulativeApproxClaimAmount": "20000000",
    "propertyApprovedClaimsCount": "4",
    "propertyApprovedClaimAmount": "1387203",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "Status as of 21-Jul-2022: Paid - 5 - 1432241 Withdrawn - 1 Rejected - 2",
    "createdDate": "22-07-2026",
    "timestamp": 1784986060366
  },
  {
    "id": "rb87cwu",
    "companyName": "Zurich Kotak General Insurance Limited (formerly Kotak General Insurance)",
    "reportingDate": "22-07-2026",
    "createdBy": "KARAN PATEL( 7045009667 )",
    "dailyClaimsReceived": "2",
    "dailyFirstVisitCompleted": "15",
    "dailyApproxClaimAmount": "450000",
    "cumulativeClaimsReceived": "100",
    "cumulativeFirstVisitCompleted": "10",
    "cumulativeApproxClaimAmount": "11805000",
    "approvedClaimsCount": "5",
    "approvedClaimAmount": "1000000",
    "motorWithdrawClaimsCount": "-",
    "rejectedClaimsCount": "-",
    "rejectionReason": "-",
    "propertyDailyClaimsReceived": "-",
    "propertyDailyFirstVisitCompleted": "-",
    "propertyDailyApproxClaimAmount": "-",
    "propertyCumulativeClaimsReceived": "-",
    "propertyCumulativeFirstVisitCompleted": "-",
    "propertyCumulativeApproxClaimAmount": "-",
    "propertyApprovedClaimsCount": "-",
    "propertyApprovedClaimAmount": "-",
    "propertyRejectedClaimsCount": "-",
    "propertyWithdrawClaimsCount": "-",
    "propertyRejectionReason": "-",
    "createdDate": "24-07-2026",
    "timestamp": 1784986060366
  }
];
